import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { ToastProvider } from './providers/ToastProvider'
import './globals.css'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      {/* <body className={font.className}> */}
      <body>
        <ToastProvider />
        {children}
      </body>
    </html>
  )
}
